const {Router} = require("express");

const router = Router();

router.use('/', require('./user'))
router.use('/profromainvoice', require('./ProFormaInvoice'))
router.use('/debitnote', require('./debitnoteRoute'))
router.use('/salesinvoice', require('./salesinvoiceRoute'))
router.use('/deliverychallan', require('./DeliveryChallanRoute'));
router.use('/payment', require('./paymentRoute'))
router.use('/item', require('./item'))
router.use('/purchaseinvoice', require('./purchaseInvoice'))
router.use('/permission', require('./permissions'))
router.use('/company', require('./company'))
router.use('/creditnote', require('./creditnote'))
router.use('/receive', require('./receiptRoute'))
router.use('/claim', require('./claim'))
router.use('/companybank', require('./companyBankdetails'))
router.use('/bom', require('./bom'))
router.use('/stock', require('./stock'))
router.use('/notification', require('./notification'))
router.use('/salary', require('./salary'))
router.use('/machine', require('./Machine'))
router.use('/dashboard', require('./dashboard'))
router.use('/itemGroup', require('./itemGroup'))
router.use('/itemCategory', require('./itemCategory'))
router.use('/itemSubCategory', require('./itemSubCategory'))
router.use('/account', require('./account'))
router.use('/ledger', require('./ledger'))
router.use('/schedule', require('./machineSchedule'))
router.use('/purchaseOrder', require('./purchaseOrder'))
router.use('/wastage', require('./wastage'))
router.use('/maintenanceType', require('./maintenanceType'))
router.use('/purpose', require('./purpose'))
router.use('/maintenance', require('./maintenance'))
router.use('/shift', require('./shift'))
router.use('/bonusConfiguration', require('./bonusConfiguration'))
router.use('/penaltyConfiguration', require('./penaltyConfiguration'))
router.use('/employee', require('./employee'))
router.use('/leave', require('./leave'))
router.use('/attendance', require('./attendance'))
router.use('/attendanceType', require('./attendanceType'))
router.use('/systemSettings', require('./systemSettings'))
router.use('/holiday', require('./holiday'))
router.use('/orderProcessing', require('./orderProcessingRoute'))
router.use('/selfExpense', require('./selfExpense'))

module.exports = router;