name: CI/CD Pipeline

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Stage
      run: |
        # Stage commands here
        echo "Staging the application"

    - name: Deploy to VPS
      env:
        SSH_USER: ${{ secrets.VPS_USERNAME }}
        SSH_PASS: ${{ secrets.VPS_PASSWORD }}
        VPS_IP: ${{ secrets.VPS_IP }}
      run: |
        sshpass -p "$SSH_PASS" ssh -o StrictHostKeyChecking=no $SSH_USER@$VPS_IP << 'EOF'
          cd /root/stage/BE
          git pull origin dev
          npm install
          npm run migrate-run
          npm run seeder-all
          pm2 restart STAGE_SERVER
        EOF
